name: release

on:
  push:
    tags:
      - 'core-v*'
      - 'react-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # npm provenance
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v4
      - run: pnpm -r install
      - run: pnpm -r build
      - run: pnpm -r check
      - run: pnpm test
      - name: Publish core
        if: startsWith(github.ref, 'refs/tags/core-v')
        run: pnpm -r --filter @consentify/core publish --access public --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish react
        if: startsWith(github.ref, 'refs/tags/react-v')
        run: pnpm -r --filter @consentify/react publish --access public --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
